
<Structures>
  <Structure Name="Roues" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="4" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="8" Vartype="String" Bytesize="6" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="14" Vartype="String" Bytesize="14" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="1240" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="2432" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="2984" Vartype="Pointer" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="2988" Vartype="4 Bytes" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="2992" Vartype="String" Bytesize="6" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="2998" Vartype="String" Bytesize="14" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="4224" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="5416" Vartype="Float" Bytesize="4" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
    </Elements>
  </Structure>
</Structures>