
<Structures>
  <Structure Name="Roues Final" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="String" Bytesize="6" Description="Type jante" DisplayMethod="Unsigned Integer" BackgroundColor="80000005"/>
      <Element Offset="1218" Vartype="Float" Bytesize="4" Description="Avant gauche" DisplayMethod="Unsigned Integer" BackgroundColor="00FF00"/>
      <Element Offset="2410" Vartype="Float" Bytesize="4" Description="Avant droit" DisplayMethod="Unsigned Integer" BackgroundColor="00FF00"/>
      <Element Offset="4202" Vartype="Float" Bytesize="4" Description="Arrière gauche" DisplayMethod="Unsigned Integer" BackgroundColor="00FF00"/>
      <Element Offset="5394" Vartype="Float" Bytesize="4" Description="Arrière droit" DisplayMethod="Unsigned Integer" BackgroundColor="00FF00"/>
    </Elements>
  </Structure>
</Structures>